import type { CSSProperties } from "react";

export const pageStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    padding: "20px",
    background:
      "radial-gradient(900px 400px at 15% 10%, #f3efe6 0%, #f8fafc 45%, #f1f5f9 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: '"Space Grotesk", "Segoe UI", ui-sans-serif, system-ui',
    color: "var(--ink)",
    ["--card" as any]: "#fffdf8",
    ["--ink" as any]: "#1f2937",
    ["--muted" as any]: "#6b7280",
    ["--border" as any]: "#e5e7eb",
    ["--accent" as any]: "#0f766e",
    ["--accentSoft" as any]: "#ccfbf1",
  },
  card: {
    background: "var(--card)",
    padding: "20px",
    borderRadius: "12px",
    width: "min(760px, 100%)",
    border: "1px solid var(--border)",
    boxShadow: "0 10px 30px rgba(15, 23, 42, 0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  header: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "12px",
    flexWrap: "wrap",
  },
  title: {
    margin: 0,
    fontSize: "20px",
    letterSpacing: "0.2px",
  },
  subtitle: {
    margin: "4px 0 0 0",
    color: "var(--muted)",
    fontSize: "13px",
  },
  meta: {
    fontSize: "12px",
    color: "var(--muted)",
    background: "#f1f5f9",
    border: "1px solid var(--border)",
    padding: "4px 8px",
    borderRadius: "999px",
  },
  buttonRow: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  formRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr auto",
    gap: "8px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  label: {
    fontWeight: 600,
  },
  input: {
    minWidth: "220px",
    height: "36px",
    padding: "0 10px",
    borderRadius: "8px",
    border: "1px solid var(--border)",
  },
  inputSm: {
    width: "100px",
    height: "34px",
    padding: "0 8px",
    borderRadius: "8px",
    border: "1px solid var(--border)",
  },
  select: {
    minWidth: "200px",
    height: "36px",
    borderRadius: "8px",
    border: "1px solid var(--border)",
    padding: "0 8px",
    background: "#ffffff",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "13px",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
  },
  primaryBtn: {
    background: "var(--accent)",
    color: "#ffffff",
    border: "none",
    padding: "0 14px",
    height: "36px",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: 600,
  },
  secondaryBtn: {
    background: "transparent",
    color: "var(--ink)",
    border: "1px solid var(--border)",
    padding: "0 12px",
    height: "36px",
    borderRadius: "8px",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "13px",
  },
  th: {
    textAlign: "left",
    padding: "8px 10px",
    borderBottom: "1px solid var(--border)",
    color: "var(--muted)",
    fontWeight: 600,
  },
  td: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border)",
    verticalAlign: "middle",
  },
  rowEven: {
    background: "#ffffff",
  },
  rowOdd: {
    background: "#f8fafc",
  },
  link: {
    color: "var(--accent)",
    textDecoration: "none",
    fontWeight: 600,
  },
  error: {
    color: "#b91c1c",
    fontSize: "13px",
  },
  success: {
    color: "#0f766e",
    fontWeight: 600,
  },
  subtext: {
    fontSize: "13px",
    color: "var(--muted)",
  },
  muted: {
    color: "var(--muted)",
  },
  empty: {
    padding: "14px 10px",
    textAlign: "center",
    color: "var(--muted)",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "16px",
  },
  tileBtn: {
    background: "var(--card)",
    borderRadius: "12px",
    padding: "20px",
    fontSize: "16px",
    fontWeight: 600,
    border: "1px solid var(--border)",
    cursor: "pointer",
    textAlign: "left",
  },
  result: {
    marginTop: "10px",
    fontSize: "14px",
    color: "var(--ink)",
  },
  marginRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  controls: {
    display: "flex",
    gap: "14px",
    flexWrap: "wrap",
  },
  grandRow: {
    fontWeight: 700,
    borderTop: "2px solid var(--border)",
  },
  statusPending: {
    background: "#fef9c3",
    color: "#854d0e",
    padding: "2px 8px",
    borderRadius: "999px",
    fontSize: "12px",
    textTransform: "capitalize",
  },
  statusSent: {
    background: "var(--accentSoft)",
    color: "#0f766e",
    padding: "2px 8px",
    borderRadius: "999px",
    fontSize: "12px",
    textTransform: "capitalize",
  },
  statusFailed: {
    background: "#fee2e2",
    color: "#b91c1c",
    padding: "2px 8px",
    borderRadius: "999px",
    fontSize: "12px",
    textTransform: "capitalize",
  },
};