import type { CSSProperties } from "react";

export const pageStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    padding: "clamp(12px, 5vw, 32px)",
    backgroundImage:
      "radial-gradient(900px 420px at 15% 10%, rgba(248, 250, 252, 0.48) 0%, rgba(248, 250, 252, 0.4) 45%, rgba(241, 245, 249, 0.38) 100%), url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=3200&q=95')",
    backgroundSize: "cover, cover",
    backgroundPosition: "center, center",
    backgroundRepeat: "no-repeat, no-repeat",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: '"Space Grotesk", "Segoe UI", ui-sans-serif, system-ui',
    color: "var(--ink)",
    fontSize: "15px",
    lineHeight: "1.6",
    ["--card" as any]: "#fffdf8",
    ["--ink" as any]: "#1f2937",
    ["--muted" as any]: "#6b7280",
    ["--border" as any]: "#e5e7eb",
    ["--accent" as any]: "#0f766e",
    ["--accentSoft" as any]: "#ccfbf1",
    overflowX: "hidden",
  },
  card: {
    background: "var(--card)",
    padding: "clamp(16px, 4vw, 32px)",
    borderRadius: "16px",
    width: "min(760px, 100%)",
    border: "1px solid var(--border)",
    boxShadow: "0 10px 40px rgba(15, 23, 42, 0.1)",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
    boxSizing: "border-box",
  },
  header: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: "20px",
    flexWrap: "wrap",
    marginBottom: "8px",
  },
  title: {
    margin: 0,
    fontSize: "clamp(20px, 5vw, 28px)",
    fontWeight: 600,
    letterSpacing: "-0.5px",
    lineHeight: "1.2",
    wordBreak: "break-word",
  },
  subtitle: {
    margin: "8px 0 0 0",
    color: "var(--muted)",
    fontSize: "clamp(13px, 2vw, 15px)",
    lineHeight: "1.5",
  },
  meta: {
    fontSize: "14px",
    color: "var(--muted)",
    background: "#f1f5f9",
    border: "1px solid var(--border)",
    padding: "6px 12px",
    borderRadius: "999px",
    whiteSpace: "nowrap",
  },
  buttonRow: {
    display: "flex",
    gap: "12px",
    flexWrap: "wrap",
  },
  formRow: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "12px",
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontWeight: 600,
    fontSize: "14px",
    color: "var(--ink)",
  },
  input: {
    minWidth: "0",
    width: "100%",
    height: "42px",
    padding: "0 14px",
    borderRadius: "10px",
    border: "1px solid var(--border)",
    fontSize: "15px",
    transition: "border-color 0.2s",
    boxSizing: "border-box",
  },
  inputSm: {
    width: "clamp(100px, 20vw, 120px)",
    height: "40px",
    padding: "0 12px",
    borderRadius: "10px",
    border: "1px solid var(--border)",
    fontSize: "15px",
    boxSizing: "border-box",
  },
  select: {
    minWidth: "0",
    width: "100%",
    height: "42px",
    borderRadius: "10px",
    border: "1px solid var(--border)",
    padding: "0 12px",
    background: "#ffffff",
    fontSize: "15px",
    boxSizing: "border-box",
  },
  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "15px",
    flexWrap: "wrap",
  },
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "8px",
    flexWrap: "wrap",
  },
  primaryBtn: {
    background: "var(--accent)",
    color: "#ffffff",
    border: "none",
    padding: "0 20px",
    height: "42px",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "15px",
    transition: "transform 0.1s, box-shadow 0.2s",
    whiteSpace: "nowrap",
  },
  secondaryBtn: {
    background: "transparent",
    color: "var(--ink)",
    border: "1px solid var(--border)",
    padding: "0 18px",
    height: "42px",
    borderRadius: "10px",
    cursor: "pointer",
    fontSize: "15px",
    whiteSpace: "nowrap",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "clamp(12px, 2vw, 15px)",
    tableLayout: "auto",
    border: "1px solid var(--border)",
  },
  th: {
    textAlign: "left",
    padding: "clamp(10px, 2vw, 14px) clamp(10px, 2vw, 16px)",
    borderBottom: "2px solid var(--border)",
    borderRight: "1px solid var(--border)",
    color: "var(--muted)",
    fontWeight: 600,
    fontSize: "clamp(11px, 1.5vw, 14px)",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    wordBreak: "break-word",
    backgroundColor: "#f8fafc",
  },
  td: {
    padding: "clamp(10px, 2vw, 14px) clamp(10px, 2vw, 16px)",
    borderBottom: "1px solid var(--border)",
    borderRight: "1px solid var(--border)",
    verticalAlign: "middle",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  rowEven: {
    background: "#ffffff",
  },
  rowOdd: {
    background: "#f8fafc",
  },
  link: {
    color: "var(--accent)",
    textDecoration: "none",
    fontWeight: 600,
    fontSize: "15px",
  },
  error: {
    color: "#b91c1c",
    fontSize: "14px",
    lineHeight: "1.5",
  },
  success: {
    color: "#0f766e",
    fontWeight: 600,
    fontSize: "15px",
  },
  subtext: {
    fontSize: "clamp(13px, 2vw, 15px)",
    color: "var(--muted)",
    lineHeight: "1.6",
  },
  muted: {
    color: "var(--muted)",
  },
  empty: {
    padding: "24px 14px",
    textAlign: "center",
    color: "var(--muted)",
    fontSize: "15px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "20px",
  },
  tileBtn: {
    background: "var(--card)",
    borderRadius: "14px",
    padding: "clamp(16px, 4vw, 28px)",
    fontSize: "clamp(14px, 3vw, 18px)",
    fontWeight: 600,
    border: "1px solid var(--border)",
    cursor: "pointer",
    textAlign: "left",
    transition: "transform 0.1s, box-shadow 0.2s",
  },
  result: {
    marginTop: "16px",
    fontSize: "15px",
    color: "var(--ink)",
    lineHeight: "1.5",
  },
  marginRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  controls: {
    display: "flex",
    gap: "20px",
    flexWrap: "wrap",
  },
  grandRow: {
    fontWeight: 700,
    borderTop: "2px solid var(--ink)",
  },
  statusPending: {
    background: "#fef9c3",
    color: "#854d0e",
    padding: "4px 12px",
    borderRadius: "999px",
    fontSize: "13px",
    textTransform: "capitalize",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  statusSent: {
    background: "var(--accentSoft)",
    color: "#0f766e",
    padding: "4px 12px",
    borderRadius: "999px",
    fontSize: "13px",
    textTransform: "capitalize",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
  statusFailed: {
    background: "#fee2e2",
    color: "#b91c1c",
    padding: "4px 12px",
    borderRadius: "999px",
    fontSize: "13px",
    textTransform: "capitalize",
    fontWeight: 500,
    whiteSpace: "nowrap",
  },
};